<a href="https://colab.research.google.com/github/ritikamalik123/Practice_ques/blob/main/Pandas_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [ ]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [ ]:
# a =
a = pd.Series([100, 200, 300, 400])

Print a, and data type

In [ ]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.Series'>

Using indexing access the element 300 from the series a.

In [ ]:
print(a[2])

300

What are the values of index for series a?

In [ ]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [ ]:
a.index = ['c', 'a', 'b', 'd']

Access the value in the series with index 'd'

In [ ]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [ ]:
print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [ ]:
# b =
b = pd.Series([800, 450, 100], index=['e', 'f', 'g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [ ]:
# a =
a = pd.concat([a, b])
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

In [ ]:
#print a again after appending b into it
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [ ]:
# a =

sorted_a = a.sort_values(ascending=False)

In [ ]:

print(sorted_a)
print(sorted_a.index)

e    800
f    450
d    400
b    300
a    200
c    100
g    100
dtype: int64
Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='str')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [ ]:
# df =
df = pd.DataFrame(a)

In [ ]:
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [ ]:

print(df.shape)

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [ ]:
# yep its same as the series.

print(df.index)

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='str')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [ ]:
print(df.head())
print(df.tail())

     0
c  100
a  200
b  300
d  400
e  800
     0
b  300
d  400
e  800
f  450
g  100

In [ ]:


df.head(3)   # first 3 rows
df.tail(2)   # last 2 rows

     0
f  450
g  100

Rename the column of the dataframe as 'points'

In [ ]:

df.columns = ['points']
print(df)

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [ ]:
#Create fruits array

# fruits =


fruits = pd.Series(
    np.random.choice(['orange', 'mango', 'apple'], size=7)
)

print(fruits)

0    orange
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
dtype: str

In [ ]:
#Create series fruits out of fruits array

# fruits =

fruits = pd.Series(fruits)
print(fruits)

0    orange
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
dtype: str

Change the index of fruits to the index of dataframe df

In [ ]:
fruits.index = df.index
print(fruits)

c    orange
a    orange
b     apple
d     apple
e     apple
f    orange
g     apple
dtype: str

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [ ]:

df['fruits'] = fruits

In [ ]:

print(df.head())

   points  fruits
c     100  orange
a     200  orange
b     300   apple
d     400   apple
e     800   apple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [ ]:
# d1 =

d1 = pd.DataFrame({
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15, 22, 20, 26, -2]
})

print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

Print(d1)

In [ ]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [ ]:


print(d1.shape)

(5, 2)

Set city = d1['city']

In [ ]:


city = d1['city']
print(city)

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: str

print city <br>
What is the type of city.

In [ ]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: str
<class 'pandas.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [ ]:
# d2 =
d2 = pd.DataFrame({
    'city': ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'],
    'Temperature': [24, 35, 36, 39]
})

print(d2)

          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [ ]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [ ]:
# d3 =
d3 = pd.concat([d1, d2], ignore_index=True)

print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengalaru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [ ]:

temp_20 = d3[d3['Temperature'] <= 20]

print(temp_20)
print("Number of cities:", len(temp_20))

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
Number of cities: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [ ]:

temp_35 = d3[d3['Temperature'] >= 35]

print(temp_35)

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [ ]:
# write function here

# def is_ut(x):

#     # write code below

# d3['is_ut'] =

In [ ]:
# print d3
d3['Union_Territory'] = d3['city'].isin(['Chandigarh', 'Pondicherry', 'Delhi'])

print(d3)

          city  Temperature  Union_Territory
0   Chandigarh           15             True
1        Delhi           22             True
2       Kanpur           20            False
3      Chennai           26            False
4       Manali           -2            False
5    Bengalaru           24            False
6   Coimbatore           35            False
7    Srirangam           36            False
8  Pondicherry           39             True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [ ]:
# write function here
def c_to_f(temp):
    return (temp * 9/5) + 32

print(c_to_f(10))

50.0

In [ ]:
# check function c_to_f(10)

print(c_to_f(10))

50.0

In [ ]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenheit'] = d3['Temperature'].apply(c_to_f)

print(d3)

          city  Temperature  Union_Territory  Temperature_F  temp_farenheit
0   Chandigarh           15             True           59.0            59.0
1        Delhi           22             True           71.6            71.6
2       Kanpur           20            False           68.0            68.0
3      Chennai           26            False           78.8            78.8
4       Manali           -2            False           28.4            28.4
5    Bengalaru           24            False           75.2            75.2
6   Coimbatore           35            False           95.0            95.0
7    Srirangam           36            False           96.8            96.8
8  Pondicherry           39             True          102.2           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [ ]:
ut_cities = d1[d1['city'].isin(['Chandigarh', 'Delhi', 'Pondicherry'])]

print(ut_cities)

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [ ]:
d1[d1['Temperature'] > (90 - 32) * 5/9]

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [ ]:
print(d1.iloc[:3])

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [ ]:
print(d1.iloc[:, -2:])

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

## Groupby

In [ ]:
# Create a dataframe using dictionary of your choice
data = {
    'Name': ['Tej', 'Diya', 'Meet', 'Jenny'],
    'Age': [22, 24, 21, 23],
    'City': ['Undach Vaniya Faliya', 'Undach Raghav Faliya', 'Pathri', 'Vadsagal']
}

df_new = pd.DataFrame(data)

print(df_new)

    Name  Age                  City
0    Tej   22  Undach Vaniya Faliya
1   Diya   24  Undach Raghav Faliya
2   Meet   21                Mumbai
3  Jenny   23                  Pune

In [ ]:
# Use Groupby of single column with aggregate sum()
result = df_new.groupby('City')['Age'].sum()

print(result)

City
Mumbai                  21
Pune                    23
Undach Raghav Faliya    24
Undach Vaniya Faliya    22
Name: Age, dtype: int64

In [ ]:
# Use Groupby of single column with aggregate count()
result = df_new.groupby('City')['Age'].count()

print(result)

City
Mumbai                  1
Pune                    1
Undach Raghav Faliya    1
Undach Vaniya Faliya    1
Name: Age, dtype: int64

In [ ]:
# Use Groupby of single column with aggregate min() and max()
result = df_new.groupby('City')['Age'].agg(['min', 'max'])

print(result)

                      min  max
City
Mumbai                 21   21
Pune                   23   23
Undach Raghav Faliya   24   24
Undach Vaniya Faliya   22   22

In [ ]:
# Use Groupby of any 2 columns with aggregate mean()
result = df_new.groupby(['City', 'Name'])['Age'].mean()

print(result)

City                  Name
Mumbai                Meet     21.0
Pune                  Jenny    23.0
Undach Raghav Faliya  Diya     24.0
Undach Vaniya Faliya  Tej      22.0
Name: Age, dtype: float64

In [ ]:
# Use Groupby of any 2 columns with aggregate min() and max()

In [ ]:
result = df_new.groupby(['City', 'Name'])['Age'].agg(['min', 'max'])

print(result)

                            min  max
City                 Name
Mumbai               Meet    21   21
Pune                 Jenny   23   23
Undach Raghav Faliya Diya    24   24
Undach Vaniya Faliya Tej     22   22

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [ ]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [ ]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[us]', length=457, freq='D')

What is the len of a?

In [ ]:
print(len(a))

457

What is the type of a?

In [ ]:
print(type(a))

<class 'pandas.DatetimeIndex'>